services:
  backend:
    build:
      context: ./backrose
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - ./backrose/media:/app/media
      - ./backrose/staticfiles:/app/staticfiles
      - ./backrose/db.sqlite3:/app/db.sqlite3
    env_file:
      - ./.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - build_volume:/app/build

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - build_volume:/usr/share/nginx/html
      - ./backrose/staticfiles:/usr/share/nginx/html/static
      - ./backrose/media:/app/media
    depends_on:
      - backend
      - frontend

volumes:
  build_volume: