version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./backrose/Dockerfile
    restart: always
    volumes:
      - ./backrose:/app
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
      - ./db.sqlite3:/app/db.sqlite3  # Mount SQLite database file
    env_file:
      - ./.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - ./staticfiles:/usr/share/nginx/html/static
      - ./media:/app/media
    depends_on:
      - backend
      - frontend