services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - build_volume:/app/build
    environment:
      - BUILD_PATH=/app/build
      - REACT_APP_API_URL=http://localhost:80/api/
      - BROWSER=none

  backend:
    build:
      context: ./backrose
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - ./backrose/media:/app/media
      - ./backrose/staticfiles:/app/staticfiles
      - ./backrose/db.sqlite3:/app/db.sqlite3
      - build_volume:/app/staticfiles 
    env_file:
      - ./backrose/.env
    depends_on:
      - frontend

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - build_volume:/usr/share/nginx/html
      - ./backrose/media:/usr/share/nginx/html/media
    depends_on:
      - backend
      - frontend

volumes:
  build_volume: