[tool.black]
line-length = 88
exclude = '''
/(
    \.venv
  | \.git
  | __pycache__
)/
'''

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "backrose.settings"
python_files = ["test_*.py"]
django_find_project = true