# Generated by Django 5.0.1 on 2025-03-24 20:02

import django.db.models.deletion
import roses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Breeder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Fungus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Rose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("title_eng", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "photo",
                    models.ImageField(
                        default="images/cap_rose.png",
                        upload_to=roses.models.get_filename,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("landing_date", models.DateField(blank=True, null=True)),
                ("observation", models.TextField(blank=True, null=True)),
                (
                    "susceptibility",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "const_width",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "const_height",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "breeder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="roses",
                        to="roses.breeder",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roses",
                        to="roses.group",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pesticide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date_added", models.DateField(blank=True, null=True)),
                (
                    "pest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pests",
                        to="roses.pest",
                    ),
                ),
                (
                    "rose",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pesticides",
                        to="roses.rose",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fungicide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date_added", models.DateField(blank=True, null=True)),
                (
                    "fungicide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fungi",
                        to="roses.fungus",
                    ),
                ),
                (
                    "rose",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fungicides",
                        to="roses.rose",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Foliage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foliage", models.TextField()),
                ("foliage_time", models.DateField(blank=True, null=True)),
                (
                    "rose",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="foliages",
                        to="roses.rose",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feeding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("basal", models.CharField(max_length=255)),
                ("basal_time", models.DateField(blank=True, null=True)),
                ("leaf", models.CharField(max_length=255)),
                ("leaf_time", models.DateField(blank=True, null=True)),
                (
                    "rose",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedings",
                        to="roses.rose",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RosePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descr", models.TextField(blank=True, null=True)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("photo", models.ImageField(upload_to=roses.models.get_filename)),
                (
                    "rose",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rosephotos",
                        to="roses.rose",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("height", models.DecimalField(decimal_places=2, max_digits=5)),
                ("width", models.DecimalField(decimal_places=2, max_digits=5)),
                ("date_added", models.DateField(blank=True, null=True)),
                (
                    "rose",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizes",
                        to="roses.rose",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descr", models.CharField(blank=True, max_length=255, null=True)),
                ("video", models.URLField()),
                (
                    "rose",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="roses.rose",
                    ),
                ),
            ],
        ),
    ]
