# Generated by Django 5.0.1 on 2025-05-09 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rose",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="roses",
                to="roses.group",
            ),
        ),
    ]
