# Generated by Django 5.0.1 on 2025-05-13 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roses", "0002_alter_rose_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="fungicide",
            name="fungi",
            field=models.ManyToManyField(
                blank=True, related_name="fungicides_new", to="roses.fungus"
            ),
        ),
        migrations.AddField(
            model_name="pesticide",
            name="pests",
            field=models.ManyToManyField(
                blank=True, related_name="pesticides_new", to="roses.pest"
            ),
        ),
        migrations.CreateModel(
            name="RoseFungicide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateField(blank=True, null=True)),
                (
                    "fungicide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="roses.fungicide",
                    ),
                ),
                (
                    "rose",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="roses.rose"
                    ),
                ),
            ],
            options={
                "unique_together": {("rose", "fungicide")},
            },
        ),
        migrations.AddField(
            model_name="fungicide",
            name="roses",
            field=models.ManyToManyField(
                blank=True,
                related_name="fungicides_new",
                through="roses.RoseFungicide",
                to="roses.rose",
            ),
        ),
        migrations.CreateModel(
            name="RosePesticide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateField(blank=True, null=True)),
                (
                    "pesticide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="roses.pesticide",
                    ),
                ),
                (
                    "rose",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="roses.rose"
                    ),
                ),
            ],
            options={
                "unique_together": {("rose", "pesticide")},
            },
        ),
        migrations.AddField(
            model_name="pesticide",
            name="roses",
            field=models.ManyToManyField(
                blank=True,
                related_name="pesticides_new",
                through="roses.RosePesticide",
                to="roses.rose",
            ),
        ),
    ]
