# Generated by Django 5.0.1 on 2025-05-13 14:01

from django.db import migrations


def migrate_data_forward(apps, schema_editor):
    Pesticide = apps.get_model("roses", "Pesticide")
    Fungicide = apps.get_model("roses", "Fungicide")

    for pesticide in Pesticide.objects.all():
        pesticide.pests.add(pesticide.pest)
        apps.get_model("roses", "RosePesticide").objects.create(
            rose=pesticide.rose, pesticide=pesticide, date_added=pesticide.date_added
        )

    for fungicide in Fungicide.objects.all():
        fungicide.fungi.add(fungicide.fungicide)
        apps.get_model("roses", "RoseFungicide").objects.create(
            rose=fungicide.rose, fungicide=fungicide, date_added=fungicide.date_added
        )


class Migration(migrations.Migration):

    dependencies = [
        ("roses", "0003_fungicide_fungi_pesticide_pests_rosefungicide_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_data_forward),
    ]
