# Generated by Django 5.0.1 on 2025-05-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roses", "0004_migrate_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fungicide",
            name="date_added",
        ),
        migrations.RemoveField(
            model_name="fungicide",
            name="fungicide",
        ),
        migrations.RemoveField(
            model_name="fungicide",
            name="rose",
        ),
        migrations.RemoveField(
            model_name="pesticide",
            name="date_added",
        ),
        migrations.RemoveField(
            model_name="pesticide",
            name="pest",
        ),
        migrations.RemoveField(
            model_name="pesticide",
            name="rose",
        ),
        migrations.AlterField(
            model_name="fungicide",
            name="fungi",
            field=models.ManyToManyField(related_name="fungicides", to="roses.fungus"),
        ),
        migrations.AlterField(
            model_name="fungicide",
            name="roses",
            field=models.ManyToManyField(
                related_name="fungicides",
                through="roses.RoseFungicide",
                to="roses.rose",
            ),
        ),
        migrations.AlterField(
            model_name="pesticide",
            name="pests",
            field=models.ManyToManyField(related_name="pesticides", to="roses.pest"),
        ),
        migrations.AlterField(
            model_name="pesticide",
            name="roses",
            field=models.ManyToManyField(
                related_name="pesticides",
                through="roses.RosePesticide",
                to="roses.rose",
            ),
        ),
    ]
