# Generated by Django 5.0.1 on 2025-05-13 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roses", "0005_remove_fungicide_date_added_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rosefungicide",
            name="fungicide",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="roses.fungicide"
            ),
        ),
        migrations.AlterField(
            model_name="rosepesticide",
            name="pesticide",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="roses.pesticide"
            ),
        ),
    ]
