# Generated by Django 5.0.1 on 2025-05-23 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roses", "0006_alter_rosefungicide_fungicide_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rosefungicide",
            name="rose",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rosefungicides",
                to="roses.rose",
            ),
        ),
        migrations.AlterField(
            model_name="rosepesticide",
            name="rose",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rosepesticides",
                to="roses.rose",
            ),
        ),
    ]
