# Generated by Django 5.0.1 on 2025-05-23 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roses", "0007_alter_rosefungicide_rose_alter_rosepesticide_rose"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rose",
            name="breeder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="roses",
                to="roses.breeder",
            ),
        ),
        migrations.AlterField(
            model_name="rose",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="roses",
                to="roses.group",
            ),
        ),
    ]
