# Generated by Django 5.0.1 on 2025-06-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="app_header",
            field=models.CharField(
                blank=True, default="Изменить название", max_length=1000
            ),
        ),
    ]
